### ISSUE TITLE
spi1d/3d 

### ISSUE THREAD

**Issue by sjkgm** [videovillage/Lattice-Issues#77] opened 2018-05-14 06:55 UTC

**Comment by sjkgm** [comment] 2018-05-14 07:03
sorry. It's just a mistake.

It is already in # 11 below..
I would like to add spi1d and 3d to LUT format support.
Do not clamp at 0-1.

**Comment by wilg** [comment] 2019-04-27 22:37
Duplicate of https://github.com/videovillage/Lattice-Issues/issues/11

**Closed by wilg** 2019-04-27 22:37 UTC
